#!/command/with-contenv bash
#shellcheck shell=bash

if [[ -n $STATION_ID ]]; then
    REASSEMBLER_ACARS_EXTRA=" --station $STATION_ID"
    MODE_ACARS_LOG="/opt/logs/acars.log"

    # Process: ZMQ --> Reassembler (ACARS) --> Remote
    ACARS_ADDITIONAL_OUTPUTS_CMD=""
    if [ ! -z "$ACARS_ADDITIONAL_OUTPUTS" ]; then
    # Split the comma-separated list of outputs
    IFS=',' read -ra ACARS_ADDITIONAL_OUTPUTS_ARRAY <<< "$ACARS_ADDITIONAL_OUTPUTS"
    # Construct the command line
    for i in "${ACARS_ADDITIONAL_OUTPUTS_ARRAY[@]}"; do
        ACARS_ADDITIONAL_OUTPUTS_CMD="${ACARS_ADDITIONAL_OUTPUTS_CMD} -o $i"
    done
    fi

    pypy3 -u /opt/iridium-toolkit/reassembler.py \
        -i zmq: -m acars -a json ${REASSEMBLER_EXTRA} ${REASSEMBLER_ACARS_EXTRA} \
        | tee "$MODE_ACARS_LOG" \
        | /opt/iridium-toolkit/iridium-acars-to-airframes.py -d $ACARS_ADDITIONAL_OUTPUTS_CMD
else
    echo "No station ID"
    sleep infinity
    exit 0
fi