#!/command/with-contenv bash
#shellcheck shell=bash

echo "Starting map-server"
cd /opt/iridium-toolkit/html

if [[ -n $LOG_MAP ]]; then
    python3 -m http.server --bind 0.0.0.0 8888 2>&1 | stdbuf -o0 awk '{print "[map-server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    python3 -m http.server --bind 0.0.0.0 8888 &> /dev/null
fi

TBG_SEND_SATS_BIN="/opt/thebaldgeek-send-sats.py"

if [[ -n $LIVEMAP_TO_TBG ]]; then
    echo "Sending sats.json to TBG"
    when-changed ./sats.json cat ./sats.json | python3 $TBG_SEND_STATS_BIN > /dev/null &
fi