#!/command/with-contenv bash
#shellcheck shell=bash

echo "Starting tbg-map-server"
cd /opt/iridium-toolkit/html

if [[ -n $LIVEMAP_TO_TBG && -n $AIRPORT_ICAO_CODE && -n $TBG_SATS_PORT ]]; then
    while true; do
        when-changed ./sats.json cat ./sats.json | python3 /opt/tbg-send-sats/thebaldgeek-send-sats-2.py
    done
else
    sleep infinity
    exit 0
fi
